### ISSUE TITLE
ARM64 Linux

### ISSUE THREAD

**Issue by ryansch** [Homebrew/homebrew-portable-ruby#145]
Would you entertain work towards cross compiling ruby 2.6.8 for ARM64/aarch64 via docker in your github actions? I've done stuff like this at work but I want to know if there's upstream interest before I invest the time.

**Comment by MikeMcQuaid** [comment]
Only if/when GitHub provides workers so we don't have to self-host this.

**Comment by ryansch** [comment]
I'll have to do an experiment to see if my existing multiarch tooling will work on github actions.
