### ISSUE TITLE
Ruby 3 support?

### ISSUE THREAD

**Issue by DillonB07** [Homebrew/homebrew-portable-ruby#146]
I would really like to use this to port a ruby application to macOS, however the project needs Ruby 3.

Would it be possible to create a release for Ruby 3?

**Comment by DillonB07** [comment]
I would really like to use this to port a ruby application to macOS, however the project needs Ruby 3.

Would it be possible to create a release for Ruby 3?

**Comment by mistydemeo** [comment]
This portable Ruby exists specifically for Homebrew, and isn't intended for other uses. Its version is tied to the Ruby shipped in the most recent version of macOS.

**Comment by DillonB07** [comment]
I see. Thanks.
