### ISSUE TITLE
How to build a portable-ruby on Linux?

### ISSUE THREAD

**Issue by coaxial** [Homebrew/homebrew-portable-ruby#168]
Instructions in the README say:

> Build a Docker image for your architecture by running:
> - `docker build -f Dockerfile --platform linux/amd64 -t homebrew-portable .`

However, the repo doesn't seem to contain any `Dockerfile`. How can I build a portable-ruby version on Linux?

**Comment by Bo98** [comment]
The same as macOS really - I'll adjust the README.

Historically it the Dockerfile would use the oldest supported glibc (i.e. old EOL Debian), but build an older glibc a part of the repo now.
