### ISSUE TITLE
Build ARM bottle for 2.3.1_1

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-portable-ruby#57]
`brew portable-package ruby` fails during `gem install byebug` because `libgmp` is not available. Installing the host's `libgmp-dev` or brew's `gmp` results in a dependency on `gmp` that the previous bottle did not have. I'll look into disabling either `gmp` or `byebug` during `configure`.

```
❯❯❯ brew portable-package ruby
…
/tmp/portable-ruby-test-20180501-10102-1nba7uc/bin/gem
install
byebug

Building native extensions.  This could take a while...
ERROR:  Error installing byebug:
        ERROR: Failed to build gem native extension.

    current directory: /tmp/portable-ruby-test-20180501-10102-1nba7uc/lib/ruby/gems/2.3.0/gems/byebug-10.0.2/ext/byebug
/tmp/portable-ruby-test-20180501-10102-1nba7uc/bin/ruby -r ./siteconf20180501-10272-i8eqdx.rb extconf.rb
creating Makefile

current directory: /tmp/portable-ruby-test-20180501-10102-1nba7uc/lib/ruby/gems/2.3.0/gems/byebug-10.0.2/ext/byebug
make "DESTDIR=" clean

current directory: /tmp/portable-ruby-test-20180501-10102-1nba7uc/lib/ruby/gems/2.3.0/gems/byebug-10.0.2/ext/byebug
make "DESTDIR="
compiling breakpoint.c
compiling locker.c
compiling context.c
compiling threads.c
compiling byebug.c
linking shared-object byebug/byebug.so
/usr/bin/ld: cannot find -lgmp
collect2: ld returned 1 exit status
Makefile:254: recipe for target 'byebug.so' failed
make: *** [byebug.so] Error 1

make failed, exit code 2
```

**Comment by MikeMcQuaid** [comment]
It feels like this may warrant a `portable-gmp` static formula.

**Comment by MikeMcQuaid** [comment]
It's not included now, it's just part of the test suite.

**Comment by sjackman** [comment]
If `gmp` is only needed for testing, can that particular test be disabled?

**Comment by sjackman** [comment]
`gmp` is not needed to build `portable-ruby`. I installed `gmp` before running `brew test portable-ruby`. `brew test portable-ruby` gives `execution expired`, because `gem install byebug` takes longer than five minutes. I confirmed that `gem install byebug` succeeds. It takes 6m46s.

**Comment by sjackman** [comment]
I've sent the ARM bottle to @MikeMcQuaid.

**Comment by MikeMcQuaid** [comment]
@sjackman Sorry, I'm not sure I understand (and I'm not confident in the new bottle until I do): what ended up being the fix/cause of the problem? Err on the side of being overly verbose, thanks ❤️

**Comment by xu-cheng** [comment]
Just my 2 cents, you may want to investigate where the `gmp` comes from. 

Neither `ruby` or `byebug` gem requires `gmp`. You may also want to try install another gem with native C extension. It seems to me that gmp may be accidentally picked up the ruby configure. Or you could check `lib/ruby/#{abi_version}/#{abi_arch}/rbconfig.rb` file.

**Comment by sjackman** [comment]
> It seems to me that gmp may be accidentally picked up by the ruby configure.

Yes, this is the case. If `libgmp.so` is available when Ruby is configured, it links opportunistically against it. The resulting `ruby` interpreter then requires `libgmp`, and compiling any native ruby modules also requires `libgmp`.

> what ended up being the fix/cause of the problem?

Problem 1. `libgmp.so` was available when `portable-ruby` was configured, and the `ruby` interpreter was linked opportunistically against it. The fix was to ensure that `libgmp.so` was not available by neither the host nor brewed when `portable-ruby` was configured.

Problem 2. `gem install byebug` takes 6m46s to execute, which exceeds the five minute timeout permitted by `brew test`. I disabled this test, and then ran `gem install byebug` afterward to ensure that it completed successfully, which it did.

`byebug` does not require `libgmp`. That was a red herring. If the `ruby` interpreter was compiled with `libgmp`, then compiling any native gems also requires `libgmp`.
