### ISSUE TITLE
Ensure DBM is available

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-portable-ruby#60]
```sh
ruby -rdbm -e "DBM.new('test')"
```
See https://github.com/Homebrew/homebrew-portable-ruby/pull/58

**Comment by sjackman** [comment]
@MikeMcQuaid I can add support for DBM to `portable-ruby` on Linux by adding a `portable-berkeley-db` formula. Shall I do that?

**Comment by MikeMcQuaid** [comment]
@sjackman Yes, seems like a good idea, thanks!

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/homebrew-portable-ruby/pull/61, thanks @sjackman!
