### ISSUE TITLE
No way to create portable formula with docker when using homebrew/brew

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/homebrew-portable-ruby#74]
`brew portable-package portable-<formula>` fails `brew linkage` for a number of formula, because homebrew is pulling the linuxbrew bottles for GCC, glibc, etc. and linking bottled glibc for portable formulae.

**Comment by zbeekman** [comment]
CC: @sjackman

**Comment by sjackman** [comment]
The following should work, though Zaak reports that it does not. 😢
```sh
brew install patchelf
brew install -s $(brew deps -n --include-build foo)
brew install --build-bottle foo
```

**Comment by zbeekman** [comment]
well, the text you added works. The problem is when trying to `brew portable-package foo` a bunch of `brew linkage` tests fail, because the `brew install -s $(brew deps -n --include-build)` step installs bottled glibc, etc.

**Comment by sjackman** [comment]
The `brew install -s $(brew deps -n --include-build)` step should not install any bottles. That's the issue that we need to troubleshoot.
