### ISSUE TITLE
Run brew portable-package on Linux CI

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew-portable-ruby#87]
See:
https://github.com/Homebrew/homebrew-portable-ruby/blob/4fe159fc08e2dffb17146c6938ce162075d60fcb/.github/workflows/tests.yml#L40-L43

Currently this doesn't do anything but it should be configured to use this repository as expected.

**Comment by sjackman** [comment]
Using a bind mounted volume may work (untested):
```
docker run -v"$PWD":/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-portable-ruby homebrew-portable-x86_64 brew portable-package portable-ruby
```
