### ISSUE TITLE
portable-ruby does not run on system with older version of glibc

### ISSUE THREAD

**Issue by runlevel5** [Homebrew/homebrew-portable-ruby#98]
I was poking into the bottled portable-ruby abit and found that on some distro I get error with missing `libcrypt.so.1` or some other glibc-related errors. I have a close look into the portable-ruby formula and I could not see any reference to static linking to glibc.

I am wondering how the project could maintain cross-distro compatability, especially on distro that does not ship with glibc, saying for example they go with musl libc.

On related topic, I learn that static linking to glibc is not so straight-forward. Therefore I've attempted to compile a binary with static linking to musl libc instead of glibc. I ran into an [issue](https://bugs.ruby-lang.org/issues/16784).

**Comment by MikeMcQuaid** [comment]
The portable Ruby for Linux does not support all distros. It's build on Debian Wheezy for compatibility.
